added install-all.sh
ibraheemdev/modern-unix pull request #65
Opened 2021-08-22 15:50 UTC by laluka

Hi folks !
Thanks for the awesome work on findings these gems ! 

So, this is just a draft, and might not be the best way to do it, but it could be used as a base for tools installation ! :)

A few ideas of improvement: 
- Some tools are conflicting, maybe, like for history : fzf XOR mcfly
- The install procedure relies too much on dependencies, maybe for every tool parse the github release page and install the package ?
- Have some sort of arg parsing to select the tools to install

That being said.. Have a nice day!
Cheers, lalu

2021-08-23 09:36 UTC, slavaGanzin commented
```
sudo apt install -y fzf
```

So it's not `install-all.sh` it's `install-all-on-ubuntu.sh`.

2021-08-23 09:41 UTC, laluka commented
> ```
> sudo apt install -y fzf
> ```
> 
> So it's not `install-all.sh` it's `install-all-on-ubuntu.sh`.

There are so many install methods for these tools, it's a first start ! :)

Maybe with the approach of automated parsing of every release page, we can at least cover unix/macos

2021-08-23 11:04 UTC, slavaGanzin commented
> Maybe with the approach of automated parsing of every release page, we can at least cover unix/macos

[AUR](https://wiki.archlinux.org/title/Arch_User_Repository) is user supported recipes for installation for Arch. A couple of times I used them to guide my installation on other *nix systems. They are easily parsable, standardized and half-time isn't Arch speciefic, so they are easier to parse then release pages.

BTW, you can install fzf with just git

2021-08-23 11:25 UTC, SuperSandro2000 commented
> There are so many install methods for these tools, it's a first start ! :)

Some of them are in Debian, some of them are in arch, some require go or rust and probably most of them are in nixpkgs. There are to many variants to cover here. I think this is a maintenance rabbit hole and not worth the effort.

2021-09-24 10:49 UTC, georgettica requested changes
I made a good effort in checking this change

It is highly opinionated and these opinions should be communicated before any action in the script takes place

Anyhow I hope my review is helpful for you

2021-09-24 10:49 UTC, georgettica commented on install-all.sh
> +if ! command -v docker &> /dev/null
With the issues docker is exhibiting now, maybe also have alternatives to docker?

2021-09-24 10:49 UTC, georgettica commented on install-all.sh
> +    go get -u github.com/cheat/cheat/cmd/cheat
In newer versions of go you can use
``` go install ```

Please investigate and bote your results

2021-09-24 10:49 UTC, georgettica commented on install-all.sh
> +    chmod +x broot
Use one tool if possible

You used curl before and now you are using wget

2021-09-24 10:49 UTC, georgettica commented on install-all.sh
> +if grep -F "alias dog" ~/.zshrc &> /dev/null
If you are checking only in zshrc, why are you adding to the bashrc aswell?

2021-09-24 10:49 UTC, georgettica commented on install-all.sh
> +    echo 'alias glances="docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -it nicolargo/glances:latest-full"' >> ~/.zshrc
I am not sure mounting the docker socket is a security best-practice

2021-09-24 10:49 UTC, georgettica commented on install-all.sh
> +    wget -qO - https://azlux.fr/repo.gpg.key | sudo apt-key add -
Same wget/curl here

2021-09-24 10:49 UTC, georgettica commented on install-all.sh
> +
Verify dependencies for the tools (curl) exist before running the script

2021-09-24 10:49 UTC, georgettica commented on install-all.sh
> +    echo 'alias gtop="docker run --rm -it --name gtop --net=host --pid=host aksakalli/gtop"' >> ~/.zshrc
Why is the running with the hosts pid?

2021-09-24 10:49 UTC, georgettica commented on install-all.sh
> +    LATEST=$(curl -s https://github.com/ClementTsang/bottom/releases | grep -oP "/[a-zA-Z0-9.:_/]+_amd64.deb" | grep -viE "nightly" | head -n 1 | sed "s#^#https://github.com&#g")
I am not sure this is the best way of pulling packages from GitHub

2021-09-24 11:31 UTC, slavaGanzin commented on install-all.sh
> +if ! command -v docker &> /dev/null
@georgettica offtopic: what are the issues?

2021-09-24 11:36 UTC, georgettica commented on install-all.sh
> +if ! command -v docker &> /dev/null
Will discuss on a private channel (via LinkedIn)

2024-09-10 19:57 UTC, closed without merging

2024-09-10 19:57 UTC, ibraheemdev commented
Don't really want to encourage installing every single tool on this list, sorry.

2024-09-11 17:34 UTC, georgettica commented
just for the sake of argument, how would you want to separate them? is there a graduation process from "not on the list" to "on the list"

2024-09-11 20:55 UTC, mgrzaslewicz commented
@laluka for ubuntu provision and updates of provisioned stack you can check
https://github.com/mgrzaslewicz/ubuntu-workstation-provision
With an easy way to include/exclude things.

I created it to have repeatable ubuntu environment. Many of the tools included were inspired by modern-unix repo

2024-09-11 21:13 UTC, laluka commented
Thanks @mgrzaslewicz ;)
But this is 3 years old, in the meantime I made my 'own offensive distro' in the form of a bunch of playbooks as well! ;)

If you want to have a look : https://github.com/laluka/lalubuntu

Cheers, and thanks for the tips still! 🌹🤙